sudo: required
services:
  - docker

before_install:
  - docker build -t karsten7/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run karsten7/react-test npm test -- --coverage

after_success:
  - docker build -t karsten7/multi-client ./client
  - docker build -t karsten7/multi-nginx ./nginx
  - docker build -t karsten7/multi-server ./server
  - docker build -t karsten7/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these images and push them to Docker Hub
  - docker push karsten7/multi-client
  - docker push karsten7/multi-nginx
  - docker push karsten7/multi-server
  - docker push karsten7/multi-worker
